/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlisuckhoe;

import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import object.TaiKhoan;
import object.DocGhi;
import object.Database;
import object.GiaoVien;
import object.Khoa;
import object.LopHoc;
import object.SinhVien;

/**
 *
 * @author duongv
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    ArrayList<TaiKhoan> tk = new ArrayList<>();
    ArrayList<LopHoc> dslop = new ArrayList<>();
    ArrayList<Khoa> dskhoa = new ArrayList<>();
    DocGhi rw = new DocGhi();
    public DangNhap() throws IOException {
        initComponents();
        getTK();
    }
    
    public void getLopKhoa()
    {
        try {
            dslop = (ArrayList<LopHoc>) rw.ReadObject("./src/data/Lop.txt");
            dskhoa = (ArrayList<Khoa>) rw.ReadObject("./src/data/Khoa.txt");
                 
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Danh sach hien tai rong");
        }
    }
    public Image getAnh()
    {
        Image icon = Toolkit.getDefaultToolkit().getImage("./src/images/logo.png");
        return icon;
    }
    
    public int checkTK(String name, String pass)
    {
        for(TaiKhoan t : tk)
        {
            if(name.equals(t.getTenDangNhap()) && pass.equals(t.getMatKhau()))
            {
                getLopKhoa();
                return t.getVaiTro();
            }
        }
        return -1;
    }
    
    public void getTK() throws IOException
    {
        try {
            tk = (ArrayList<TaiKhoan>) rw.ReadObject("./src/data/TaiKhoan.txt");
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra. Liên hệ với quản trị viên của bạn!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        tf_pass = new javax.swing.JTextField();
        bt_login = new javax.swing.JButton();
        menu_gv = new javax.swing.JMenuBar();
        m_gvTroGiup = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhóm 5 - Quản lý sức khỏe");
        setBackground(new java.awt.Color(250, 250, 250));
        setIconImage(getAnh());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setText("Tên đăng nhập");

        jLabel2.setText("Mật khẩu");

        bt_login.setText("Đăng nhập");
        bt_login.setToolTipText("");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tf_pass, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(bt_login)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        menu_gv.setBackground(new java.awt.Color(250, 250, 250));

        m_gvTroGiup.setText("Trợ Giúp");

        jMenuItem1.setText("Liên hệ");
        m_gvTroGiup.add(jMenuItem1);

        jMenuItem2.setText("Thông tin ứng dụng");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        m_gvTroGiup.add(jMenuItem2);

        menu_gv.add(m_gvTroGiup);

        setJMenuBar(menu_gv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
        String name = tf_name.getText();
        String pass = tf_pass.getText();
        
        int vaitro = checkTK(name, pass);
            if (vaitro == -1) {
                JOptionPane.showMessageDialog(null, "Tên đăng nhập hoặc mật khẩu không đúng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else
            {
                if (vaitro == 0) {
                    rw = new DocGhi();
                try {
                    ArrayList<SinhVien> dssv = (ArrayList<SinhVien>) rw.ReadObject("./src/data/SinhVien.txt");
                    for(TaiKhoan t :tk){
                        if(t.getTenDangNhap().equals(name)){
                            for(SinhVien s : dssv)
                                {
                                    if (s.getMaSV().equals(t.getMaDoiTuong())) {
                                        for (LopHoc l : dslop) {
                                            if (s.getMaLop().equals(l.getMaLop())) {
                                                for (Khoa k : dskhoa) {
                                                    if (k.getMaKhoa().equals(l.getMaKhoa())) {
                                                        TrangChuSinhVien frame = new TrangChuSinhVien(s, l, k);
                                                        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                                                        Container contentPane = frame.getContentPane();
                                                        frame.setVisible(true);
                                                        this.setVisible(false);
                                                        break;
                                                    }
                                                }
                                            break;
                                            }
                                        }
                                    break;
                                    }
                                }
                        }
                    }
                    
                } catch (IOException | ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Danh sach hien tai rong");
                }
                
                
            }else if (vaitro == 1) {
                rw = new DocGhi();
                try {
                    ArrayList<GiaoVien> dsgv = (ArrayList<GiaoVien>) rw.ReadObject("./src/data/GiaoVien.txt");
                    for(TaiKhoan t : tk){
                        if(t.getTenDangNhap().equals(name)){
                            for(GiaoVien s : dsgv)
                                {
                                    if (s.getMaGV().equals(t.getMaDoiTuong())) {
                                        for (LopHoc l : dslop) {
                                            if (s.getMaGV().equals(l.getMaGV())) {
                                                for (Khoa k : dskhoa) {
                                                    if (k.getMaKhoa().equals(l.getMaKhoa())) {
                                                        TrangChuGiaoVien frame = new TrangChuGiaoVien(s, k, l);
                                                        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                                                        Container contentPane = frame.getContentPane();
                                                        frame.setVisible(true);
                                                        this.setVisible(false);
                                                        break;
                                                    }
                                                }
                                            break;
                                            }
                                        }
                                    break;
                                    }
                                }
                        }
                    }
                    
                    
                    
                } catch (IOException | ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Danh sach hien tai rong");
                }
                
            }else if (vaitro == 2) {
                rw = new DocGhi();
                try {
                    ArrayList<GiaoVien> dsgv = (ArrayList<GiaoVien>) rw.ReadObject("./src/data/GiaoVien.txt");
                    for(TaiKhoan t : tk){
                        if(t.getTenDangNhap().equals(name)){
                            for(GiaoVien s : dsgv)
                                {
                                    if(s.getMaGV().equals(t.getMaDoiTuong())){
                                        for (Khoa k : dskhoa) {
                                                    if (k.getMaGV().equals(s.getMaGV())) {
                                                        TrangChuNguoiQuanTri frame = new TrangChuNguoiQuanTri(s, k);
                                                        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                                                        Container contentPane = frame.getContentPane();
                                                        frame.setVisible(true);
                                                        this.setVisible(false);
                                                        System.out.println(s.toString());
                                                        System.out.println(k.toString());
                                                        
                                                        break;
                                                    }
                                                }
                                    break;
                                    }
                                    
                                }
                            break;
                        }
                    }
                    
                    
                    
                } catch (IOException | ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Danh sach hien tai rong");
                }
                
            }
            }

    }//GEN-LAST:event_bt_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DangNhap().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu m_gvTroGiup;
    private javax.swing.JMenuBar menu_gv;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_pass;
    // End of variables declaration//GEN-END:variables

    private URL getResource(Path strPath) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
