/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlisuckhoe;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import object.DocGhi;
import object.DonKBYTGiaoVien;
import object.GiaoVien;
import object.Khoa;
import object.LichSu;

/**
 *
 * @author ducth
 */
public class GVKhaiBao extends javax.swing.JFrame {
    
    private GiaoVien gv;
    private Khoa khoa;
    
    
//    private GiaoVien gv = new GiaoVien("GV01", "Nguyễn Văn Mạnh", "K01");
//    private Khoa khoa = new Khoa("K01", "CNTT", "GV01");
//    
    
    private DonKBYTGiaoVien kbyt = new DonKBYTGiaoVien();
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    Date date = new Date();
    String ngayKB = df.format(date);
    
    DocGhi rw = new DocGhi();
    
    ArrayList<DonKBYTGiaoVien> dskbgv = new ArrayList<>();
    /**
     * Creates new form GVKB
     */
    public Image getAnh()
    {
        Image icon = Toolkit.getDefaultToolkit().getImage("./src/images/logo.png");
        return icon;
    }
    public GVKhaiBao() {
        initComponents();
        groupBT();
        txtNgay.setText(ngayKB);
//        kbyt.setNgayKhaiBao(ngayKB);
        getDanhSach();
    }
    public void groupBT()
    {
        ButtonGroup bg = new ButtonGroup();
        bg.add(rb_14Co);
        bg.add(rb_14Khong);
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(rb_14Co1);
        bg1.add(rb_14Khong1);
        ButtonGroup bg2 = new ButtonGroup();
        bg2.add(rb_14Co2);
        bg2.add(rb_14Khong2);
        ButtonGroup bg3 = new ButtonGroup();
        bg3.add(rb_14Co3);
        bg3.add(rb_14Khong3);
        ButtonGroup bg4 = new ButtonGroup();
        bg4.add(rb_14Co4);
        bg4.add(rb_14Khong4);
    }
    public void getDanhSach(){
        try {
            dskbgv = (ArrayList<DonKBYTGiaoVien>) rw.ReadObject("./src/data/KBYTGV.txt");
//            for(DonKBYTGiaoVien i : dskbgv){
//                    System.out.println(i.getMaGV() + i.getTenGV());
//                }
        } catch (IOException ex) {
            Logger.getLogger(GVKhaiBao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GVKhaiBao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public GiaoVien getGv() {
        return gv;
    }

    public void setGv(GiaoVien gv) {
        this.gv = gv;
    }

    public Khoa getKhoa() {
        return khoa;
    }

    public void setKhoa(Khoa khoa) {
        this.khoa = khoa;
    }

    public GVKhaiBao(GiaoVien gv, Khoa khoa) {
        this.gv = gv;
        this.khoa = khoa;
         initComponents();
         kbyt.setNgayKhaiBao(ngayKB);
         getDanhSach();
    }
    public void addLichSu(LichSu s)
    {
        DocGhi rw = new DocGhi();
        ArrayList<LichSu> dsls;
        try {
            dsls = (ArrayList<LichSu>) rw.ReadObject("./src/data/LichSu.txt");
            s.setStt(Integer.toString(dsls.size()+1));
            dsls.add(s);
            rw.WriteObject("./src/data/LichSu.txt", dsls);
        } catch (IOException ex) {
            Logger.getLogger(GVKhaiBao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GVKhaiBao.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenGV = new javax.swing.JTextField();
        tieude_ngay = new javax.swing.JLabel();
        txtMaGV = new javax.swing.JTextField();
        txtTenKhoa = new javax.swing.JTextField();
        txtNgay = new javax.swing.JTextField();
        rb_14Co = new javax.swing.JRadioButton();
        rb_14Khong = new javax.swing.JRadioButton();
        rb_14Khong1 = new javax.swing.JRadioButton();
        rb_14Co1 = new javax.swing.JRadioButton();
        rb_14Co2 = new javax.swing.JRadioButton();
        rb_14Khong2 = new javax.swing.JRadioButton();
        rb_14Co3 = new javax.swing.JRadioButton();
        tieude_magv = new javax.swing.JLabel();
        tieude_tengv = new javax.swing.JLabel();
        rb_14Khong3 = new javax.swing.JRadioButton();
        rb_14Co4 = new javax.swing.JRadioButton();
        tieude_khoa = new javax.swing.JLabel();
        rb_14Khong4 = new javax.swing.JRadioButton();
        tieude = new javax.swing.JLabel();
        bt_khaibao = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menu_gv = new javax.swing.JMenuBar();
        m_gvTrangChu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Khai báo y tế");
        setBackground(new java.awt.Color(250, 250, 250));
        setIconImage(getAnh());

        txtTenGV.setEditable(false);
        txtTenGV.setText(gv.getTenGV());

        tieude_ngay.setText("Ngày");

        txtMaGV.setEditable(false);
        txtMaGV.setText(gv.getMaGV());

        txtTenKhoa.setEditable(false);
        txtTenKhoa.setText(khoa.getTenKhoa());

        txtNgay.setEditable(false);
        txtNgay.setText(ngayKB);

        rb_14Co.setText("Có");

        rb_14Khong.setText("Không");

        rb_14Khong1.setText("Không");

        rb_14Co1.setText("Có");

        rb_14Co2.setText("Có");

        rb_14Khong2.setText("Không");

        rb_14Co3.setText("Có");

        tieude_magv.setText("Mã giáo viên");

        tieude_tengv.setText("Tên giáo viên");

        rb_14Khong3.setText("Không");

        rb_14Co4.setText("Có");

        tieude_khoa.setText("Khoa");

        rb_14Khong4.setText("Không");

        tieude.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tieude.setText("Khai Báo Y Tế");

        bt_khaibao.setText("Khai Báo");
        bt_khaibao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_khaibaoActionPerformed(evt);
            }
        });

        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel1.setText("Trong vòng 14 ngày qua,Anh/Chị có thấy xuất hiện ít nhất 1 trong");

        jLabel2.setText("các dấu hiệu: sốt, ho, khó thở, viêm phổi, đau họng, mệt mỏi, thay");

        jLabel3.setText("đổi vị giác không?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setText("Trong vòng 14 ngày qua Anh/Chị có tiếp xúc với:");

        jLabel5.setText("Người bệnh hoặc nghi ngờ mắc bệnh Covid-19");

        jLabel6.setText("Người từ nước có bệnh Covid-19");

        jLabel7.setText("Người bệnh có biểu hiện sốt, ho, khó thở, viêm phổi");

        jLabel8.setText("Người bệnh hoặc nghi ngờ mắc bệnh đậu mùa khỉ");

        m_gvTrangChu.setText("Trang Chủ");
        m_gvTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_gvTrangChuMouseClicked(evt);
            }
        });
        menu_gv.add(m_gvTrangChu);

        setJMenuBar(menu_gv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_14Khong, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_14Co, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tieude, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tieude_tengv, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tieude_magv, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTenGV, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                            .addComponent(txtMaGV))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tieude_khoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tieude_ngay, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(txtTenKhoa)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb_14Co1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rb_14Co2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rb_14Co3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rb_14Co4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(bt_khaibao, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_14Khong1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rb_14Khong2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rb_14Khong3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rb_14Khong4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tieude, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txtTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tieude_magv)
                            .addComponent(tieude_khoa)
                            .addComponent(txtTenKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tieude_tengv)
                            .addComponent(tieude_ngay)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb_14Co)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rb_14Khong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_14Co1)
                    .addComponent(rb_14Khong1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_14Co2)
                    .addComponent(rb_14Khong2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_14Co3)
                    .addComponent(rb_14Khong3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_14Co4)
                    .addComponent(rb_14Khong4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(bt_khaibao)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_khaibaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_khaibaoActionPerformed
        try {
            int err = 0;
            kbyt.setMaGV(txtMaGV.getText());
            kbyt.setTenGV(txtTenGV.getText());
            kbyt.setKhoa(txtTenKhoa.getText());
            kbyt.setNgayKhaiBao(ngayKB);
            if(rb_14Co.isSelected()){
                kbyt.setCoTrieuChung(true);
            }else if(rb_14Khong.isSelected()){
                kbyt.setCoTrieuChung(false);
            }else
            {
                err = 1;
            }
            if(rb_14Co1.isSelected()){
                kbyt.setTiepXucNguoiBenh(true);
            }else if(rb_14Khong1.isSelected()){
                kbyt.setTiepXucNguoiBenh(false);
            }else
            {
                err = 1;
            }
            if(rb_14Co2.isSelected()){
                kbyt.setTiepXucNguoiTuNuocCoBenh(true);
            }else if(rb_14Khong2.isSelected()){
                kbyt.setTiepXucNguoiTuNuocCoBenh(false);
            }else
            {
                err = 1;
            }
            if(rb_14Co3.isSelected()){
                kbyt.setTiepXucNguoiBenhCoBieuHien(true);
            }else if(rb_14Khong3.isSelected()){
                kbyt.setTiepXucNguoiBenhCoBieuHien(false);
            }else
            {
                err = 1;
            }
            if(rb_14Co4.isSelected()){
                kbyt.setTiepXucNguoiBenhDauMua(true);
            }else if(rb_14Khong4.isSelected()){
                kbyt.setTiepXucNguoiBenhDauMua(false);
            }else
            {
                err = 1;
            }
            
            DocGhi rw = new DocGhi();
        
        
        
        if(err == 1)
            JOptionPane.showMessageDialog(null, "Bạn cần chọn Có hoặc Không");
        else
        {
            dskbgv.add(kbyt);
            LichSu s = new LichSu(kbyt.getMaGV(),"Khai báo y tế", kbyt.getNgayKhaiBao(), kbyt);
            addLichSu(s);
            rw.WriteObject("./src/data/KBYTGV.txt", dskbgv);
//            try {
//                ArrayList<DonKBYTGiaoVien> check = (ArrayList<DonKBYTGiaoVien>)rw.ReadObject("./src/data/KBYTGV.txt");
//                for(DonKBYTGiaoVien i : check){
//                    System.out.println(i.getMaGV() + i.getTenGV());
//                }
//            } catch (FileNotFoundException ex) {
//                Logger.getLogger(GVNghi.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(GVNghi.class.getName()).log(Level.SEVERE, null, ex);
//            }
            dispose();
        }
        } catch (IOException ex) {
            Logger.getLogger(GVKhaiBao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_khaibaoActionPerformed

    private void m_gvTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_gvTrangChuMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_m_gvTrangChuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GVKhaiBao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GVKhaiBao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GVKhaiBao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GVKhaiBao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GVKhaiBao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_khaibao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu m_gvTrangChu;
    private javax.swing.JMenuBar menu_gv;
    private javax.swing.JRadioButton rb_14Co;
    private javax.swing.JRadioButton rb_14Co1;
    private javax.swing.JRadioButton rb_14Co2;
    private javax.swing.JRadioButton rb_14Co3;
    private javax.swing.JRadioButton rb_14Co4;
    private javax.swing.JRadioButton rb_14Khong;
    private javax.swing.JRadioButton rb_14Khong1;
    private javax.swing.JRadioButton rb_14Khong2;
    private javax.swing.JRadioButton rb_14Khong3;
    private javax.swing.JRadioButton rb_14Khong4;
    private javax.swing.JLabel tieude;
    private javax.swing.JLabel tieude_khoa;
    private javax.swing.JLabel tieude_magv;
    private javax.swing.JLabel tieude_ngay;
    private javax.swing.JLabel tieude_tengv;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtTenGV;
    private javax.swing.JTextField txtTenKhoa;
    // End of variables declaration//GEN-END:variables
}
