/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlisuckhoe;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.nio.channels.FileChannel;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import object.DocGhi;
import object.DonXinNghiSV;
import object.Khoa;
import object.LichSu;
import object.LopHoc;
import object.SinhVien;
import object.Database;
import object.ThongBao;

/**
 *
 * @author ducth
 */

public class SVXinNghi extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private SinhVien sv = new SinhVien("SV01", "Nguyễn Minh Anh", "Nữ", "012345678", "abc@gmail.com", "2001-01-16", "L01");
    
    private LopHoc lh = new LopHoc("L01", "IT01", 4, 14, "K01", "GV01");
        
    private Khoa k = new Khoa("K01", "CNTT", "GV01");
//    
//    private SinhVien sv;
//    private LopHoc lh;
//    private Khoa k;
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    Date date = new Date();
    String ngayGui = df.format(date);
    ArrayList<String> filePath = new ArrayList<>();
    public SinhVien getSv() {
        return sv;
    }

    public void setSv(SinhVien sv) {
        this.sv = sv;
    }

    public LopHoc getLh() {
        return lh;
    }

    public void setLh(LopHoc lh) {
        this.lh = lh;
    }

    public Khoa getK() {
        return k;
    }

    public void setK(Khoa k) {
        this.k = k;
    }
    
    public SVXinNghi() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(rb_co);
        bg.add(rb_khong);
    }
    public SVXinNghi(SinhVien s, LopHoc lh, Khoa kh) {
        this.sv =s;
        this.lh = lh;
        this.k = kh;
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(rb_co);
        bg.add(rb_khong);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_ngay = new javax.swing.JTextField();
        tieude_ngay6 = new javax.swing.JLabel();
        bt_gui = new javax.swing.JButton();
        bt_file = new javax.swing.JButton();
        tieude_ngaybd = new javax.swing.JLabel();
        file_name = new javax.swing.JLabel();
        tieude_masv = new javax.swing.JLabel();
        text_ngaybd = new javax.swing.JTextField();
        tieude_khoa1 = new javax.swing.JLabel();
        tieude_tensv = new javax.swing.JLabel();
        tieude_ngay3 = new javax.swing.JLabel();
        text_lop = new javax.swing.JTextField();
        tieude_khoa = new javax.swing.JLabel();
        text_ngaykt = new javax.swing.JTextField();
        tieude = new javax.swing.JLabel();
        tieude_ngay4 = new javax.swing.JLabel();
        text_tensv = new javax.swing.JTextField();
        cb_lydo = new javax.swing.JComboBox<>();
        tieude_ngay = new javax.swing.JLabel();
        tieude_ngay5 = new javax.swing.JLabel();
        text_msv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_chitiet = new javax.swing.JTextArea();
        text_khoa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rb_co = new javax.swing.JRadioButton();
        rb_khong = new javax.swing.JRadioButton();
        menu_gv = new javax.swing.JMenuBar();
        m_gvTrangChu = new javax.swing.JMenu();
        m_gvTroGiup = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text_ngay.setEditable(false);
        text_ngay.setText(ngayGui);

        tieude_ngay6.setText("Các tài liệu/hình ảnh liên quan:");

        bt_gui.setText("Gửi");
        bt_gui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guiActionPerformed(evt);
            }
        });

        bt_file.setText("Chọn file");
        bt_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fileActionPerformed(evt);
            }
        });

        tieude_ngaybd.setText("Ngày bắt đầu");

        file_name.setText("Bạn chưa chọn file");

        tieude_masv.setText("Mã sinh viên");

        text_ngaybd.setText("dd/mm/yyyy");

        tieude_khoa1.setText("Lớp");

        tieude_tensv.setText("Tên sinh viên");

        tieude_ngay3.setText("Ngày kết thúc");

        text_lop.setEditable(false);
        text_lop.setText(lh.getTenLop());

        tieude_khoa.setText("Khoa");

        text_ngaykt.setText("dd/mm/yyyy");
        text_ngaykt.setToolTipText("");

        tieude.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tieude.setText("Đơn Xin Nghỉ Phép");

        tieude_ngay4.setText("Lý do xin nghỉ");

        text_tensv.setEditable(false);
        text_tensv.setText(sv.getTenSV());

        cb_lydo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ốm nhập viện", "Việc cá nhân", "Mắc Covid-19", "Khác" }));

        tieude_ngay.setText("Ngày gửi");

        tieude_ngay5.setText("Mô tả chi tiết:");

        text_msv.setEditable(false);
        text_msv.setText(sv.getMaSV());

        text_chitiet.setColumns(20);
        text_chitiet.setRows(5);
        jScrollPane1.setViewportView(text_chitiet);

        text_khoa.setEditable(false);
        text_khoa.setText(k.getTenKhoa());

        jLabel5.setText("Bạn có muốn tham gia lớp học trực tuyến không?");

        rb_co.setText("Có");

        rb_khong.setText("Không");

        m_gvTrangChu.setText("Trang Chủ");
        m_gvTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_gvTrangChuMouseClicked(evt);
            }
        });
        menu_gv.add(m_gvTrangChu);

        m_gvTroGiup.setText("Trợ Giúp");
        menu_gv.add(m_gvTroGiup);

        setJMenuBar(menu_gv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tieude_ngay6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(190, 190, 190)
                                            .addComponent(bt_file)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(file_name, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(199, 199, 199)
                                    .addComponent(bt_gui, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(rb_co, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(rb_khong, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tieude_ngay5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tieude_ngay4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tieude_tensv)
                                .addComponent(tieude_masv))
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_msv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_tensv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cb_lydo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tieude_khoa1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tieude_khoa, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tieude_ngay, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tieude_ngay3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tieude_ngaybd, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_ngaykt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_ngaybd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_lop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(text_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tieude, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tieude, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tieude_ngay)
                        .addGap(27, 27, 27)
                        .addComponent(tieude_khoa)
                        .addGap(29, 29, 29)
                        .addComponent(tieude_khoa1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cb_lydo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tieude_ngay4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_msv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tieude_masv))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_tensv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tieude_tensv)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(text_lop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(tieude_ngaybd)
                                        .addGap(27, 27, 27)
                                        .addComponent(tieude_ngay3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(text_ngaybd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(text_ngaykt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_co)
                    .addComponent(rb_khong)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tieude_ngay5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(tieude_ngay6))
                    .addComponent(bt_file)
                    .addComponent(file_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(bt_gui)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guiActionPerformed
        // TODO add your handling code here:
        DocGhi rw = new DocGhi();
        int err = 0;
        ArrayList<DonXinNghiSV> kb;
        try {
            kb = (ArrayList<DonXinNghiSV>) rw.ReadObject("./src/data/DonXNSV.txt");
                 
        } catch (IOException | ClassNotFoundException ex) {
            kb = new ArrayList<>();
        }
        DonXinNghiSV d = new DonXinNghiSV();
        d.setTrangThai("Chờ"); 
        d.setMaSV(sv.getMaSV());
        d.setTenSV(sv.getTenSV());
        d.setKhoa(k.getTenKhoa());
        d.setLop(lh.getTenLop());
        d.setNgayGui(text_ngay.getText());
        d.setNgayBatDau(text_ngaybd.getText());
        d.setNgayKetThuc(text_ngaykt.getText());
        d.setLyDo((String)cb_lydo.getSelectedItem());
        if(rb_co.isSelected())
        {
            d.setHocOnl(true);
            
        }else if(rb_khong.isSelected())
        {
            d.setHocOnl(false);
        }
        else
        {
            err = 1;
        }
        Date d1 = new Date();
        Date d2 = new Date();;
        try {
            d1 = df.parse(d.getNgayBatDau());
            d2 = df.parse(d.getNgayKetThuc());
        } catch (ParseException ex) {
            err = 3;
        }
        if(!df.format(d1).equals(text_ngaybd.getText()) || !df.format(d2).equals(text_ngaykt.getText()))
        {
            err = 3;
        }
        if(d1.after(d2) || !date.before(d1))
        {
            err = 2;
        }
//        if(index == 0)
//        {
//            d.setLyDo("Ốm nhập viện");
//        }
//        if(index == 1)
//        {
//            d.setLyDo("Việc cá nhân");
//        }
//        if(index == 2)
//        {
//            d.setLyDo("Mắc Covid-19");
//        }
//        if(index == 3)
//        {
//            d.setLyDo("Khác");
//        }
        
        d.setChiTiet(text_chitiet.getText());
        d.setTaiLieuLienQuan(file_name.getText());
        if(d.getTaiLieuLienQuan().equals("Bạn chưa chọn file"))
            JOptionPane.showMessageDialog(null, "Bạn cần gửi kèm tài liệu");
        else if(err == 1)
        {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn Có hoặc Không");
        }
        else if(err == 3)
        {
            JOptionPane.showMessageDialog(null, "Bạn cần nhập ngày theo định dạng dd/MM/yyyy");
        }
        else if(err == 2)
        {
            JOptionPane.showMessageDialog(null, "Bạn cần nhập ngày bắt đầu sau kết thúc/ngày bắt từ thời điểm hiện tại");
        }
        else
        {
            kb.add(d);
          
            try {
                rw.WriteObject("./src/data/DonXNSV.txt", kb);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(SVXinNghi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            LichSu s = new LichSu(d.getMaSV(),"Xin nghỉ", d.getNgayGui(), d);
            addLichSu(s);
            ThongBao t = new ThongBao(d.getMaSV(),lh.getMaGV(),"Xin nghỉ", d.getNgayGui(), d);
            addThongBao(t);
            
            
            for(String sourceFile : filePath)
            {
                sourceFile=sourceFile.replace("\\","/");
                sourceFile=sourceFile.replace(d.getTaiLieuLienQuan(),"");
                sourceFile=sourceFile.trim();
                System.out.println(sourceFile);
                // sourceFolder: thu muc nguon duoc copy
                Path sourceFolder = Paths.get(sourceFile);
                // targetFolder: thu muc dich duoc copy den
                Path targetFolder = Paths.get("./src/images/"+d.getTaiLieuLienQuan());
                try {
                    // goi phuong thuc copy
                    copyFolder(sourceFolder, targetFolder);
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(SVXinNghi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
            
            
            //console check
//            ArrayList<DonXinNghiSV> ds01;
//            try {
//                ds01 = (ArrayList<DonXinNghiSV>) rw.ReadObject("./src/data/DonXNSV.txt");
//                for(DonXinNghiSV svt : ds01)
//            {
//                System.out.println(svt.toString());
//                
//            }
//            } catch (IOException ex) {
//                java.util.logging.Logger.getLogger(SVXinNghi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            } catch (ClassNotFoundException ex) {
//                java.util.logging.Logger.getLogger(SVXinNghi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            }
            
        
            dispose();
        }
    }//GEN-LAST:event_bt_guiActionPerformed
    private static void copyFolder(Path sourcePath, Path targetPath) throws IOException 
    {
        
            // copy file tu thuc muc nguon den thu muc dich
            Files.copy(sourcePath, targetPath,StandardCopyOption.REPLACE_EXISTING);
            System.out.println("File da duoc copy ");
        
    }
    public void addLichSu(LichSu s)
    {
        DocGhi rw = new DocGhi();
        try {
            
            ArrayList<LichSu> dsls = (ArrayList<LichSu>) rw.ReadObject("./src/data/LichSu.txt");
            s.setStt(Integer.toString(dsls.size()+1));
            dsls.add(s);
            rw.WriteObject("./src/data/LichSu.txt", dsls);
            
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Danh sach hien tai rong");
        }
    }
    public void addThongBao(ThongBao s)
    {
        DocGhi rw = new DocGhi();
        try {
            
            ArrayList<ThongBao> dstb = (ArrayList<ThongBao>) rw.ReadObject("./src/data/ThongBao.txt");
            s.setStt(Integer.toString(dstb.size()+1));
            dstb.add(s);
            rw.WriteObject("./src/data/ThongBao.txt", dstb);
            
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Danh sach hien tai rong");
        }
    }
    private void bt_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fileActionPerformed
        // TODO add your handling code here:
        // if the user presses the save button show the save dialog
        // if the user presses the save button show the save dialog
//        String com = evt.getActionCommand();

//        if (com.equals("Gửi")) {
//            // create an object of JFileChooser class
//            JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
//
//            // allow multiple file selection
//            j.setMultiSelectionEnabled(true);
//
//            // invoke the showsSaveDialog function to show the save dialog
//            int r = j.showSaveDialog(null);
//
//            if (r == JFileChooser.APPROVE_OPTION) {
//                // get the selelcted files
//                File files[] = j.getSelectedFiles();
//
//                int t = 0;
//                // set text to blank
//                file_name.setText("");
//
//                // set the label to the path of the selected files
//                while (t++ < files.length)
//                file_name.setText(file_name.getText() + "; " + files[t - 1].getName());
//            }
//            // if the user cancelled the operation
//            else
//            file_name.setText("Bạn chưa chọn file");
//        }
//
//        // if the user presses the open dialog show the open dialog
//        else {
            // create an object of JFileChooser class
            JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

            // allow multiple file selection
            j.setMultiSelectionEnabled(true);

            // invoke the showsOpenDialog function to show the save dialog
            int r = j.showOpenDialog(null);

            if (r == JFileChooser.APPROVE_OPTION) {
                // get the selelcted files
                File files[] = j.getSelectedFiles();

                // set text to blank
                file_name.setText("");

                int t = 0;
                // set the label to the path of the selected files
                while (t++ < files.length){
                    file_name.setText(file_name.getText() + " " + files[t - 1].getName());
                    filePath.add(file_name.getText() + " " + files[t - 1].getAbsolutePath());
                }
                
            }
            // if the user cancelled the operation
            else
            file_name.setText("Bạn chưa chọn file");
//        }
    }//GEN-LAST:event_bt_fileActionPerformed

    private void m_gvTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_gvTrangChuMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_m_gvTrangChuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SVXinNghi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SVXinNghi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SVXinNghi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SVXinNghi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SVXinNghi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_file;
    private javax.swing.JButton bt_gui;
    private javax.swing.JComboBox<String> cb_lydo;
    private javax.swing.JLabel file_name;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu m_gvTrangChu;
    private javax.swing.JMenu m_gvTroGiup;
    private javax.swing.JMenuBar menu_gv;
    private javax.swing.JRadioButton rb_co;
    private javax.swing.JRadioButton rb_khong;
    private javax.swing.JTextArea text_chitiet;
    private javax.swing.JTextField text_khoa;
    private javax.swing.JTextField text_lop;
    private javax.swing.JTextField text_msv;
    private javax.swing.JTextField text_ngay;
    private javax.swing.JTextField text_ngaybd;
    private javax.swing.JTextField text_ngaykt;
    private javax.swing.JTextField text_tensv;
    private javax.swing.JLabel tieude;
    private javax.swing.JLabel tieude_khoa;
    private javax.swing.JLabel tieude_khoa1;
    private javax.swing.JLabel tieude_masv;
    private javax.swing.JLabel tieude_ngay;
    private javax.swing.JLabel tieude_ngay3;
    private javax.swing.JLabel tieude_ngay4;
    private javax.swing.JLabel tieude_ngay5;
    private javax.swing.JLabel tieude_ngay6;
    private javax.swing.JLabel tieude_ngaybd;
    private javax.swing.JLabel tieude_tensv;
    // End of variables declaration//GEN-END:variables
}
