/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlisuckhoe;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import object.DocGhi;
import object.DonXinNghiSV;
import object.Khoa;
import object.LopHoc;
import object.SinhVien;

/**
 *
 * @author ducth
 */

public class SVXinNghiChiTiet extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
//    private SinhVien sv = new SinhVien("SV01", "Nguyễn Minh Anh", "Nữ", "012345678", "abc@gmail.com", "2001-01-16", "L01");
//    
//    private LopHoc lh = new LopHoc("L01", "IT01", 4, 14, "K01", "GV01");
//        
//    private Khoa k = new Khoa("K01", "CNTT", "GV01");
//    
    private DonXinNghiSV d;
    
    public SVXinNghiChiTiet() {
        initComponents();
    }
    public SVXinNghiChiTiet(DonXinNghiSV d) {
        this.d = d;
        initComponents();
    }
    public int getIndex()
    {
        if(d.getLyDo().equals("Ốm nhập viện"))
        {
            return 0;
        }
        if(d.getLyDo().equals("Việc cá nhân"))
        {
            return 1;
        }
        if(d.getLyDo().equals("Mắc Covid-19"))
        {
            return 2;
        }
        if(d.getLyDo().equals("Khác"))
        {
            return 3;
        }
        return -1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_ngay = new javax.swing.JTextField();
        tieude_ngay6 = new javax.swing.JLabel();
        bt_xem = new javax.swing.JButton();
        tieude_ngaybd = new javax.swing.JLabel();
        file_name = new javax.swing.JLabel();
        tieude_masv = new javax.swing.JLabel();
        text_ngaybd = new javax.swing.JTextField();
        tieude_khoa1 = new javax.swing.JLabel();
        tieude_tensv = new javax.swing.JLabel();
        tieude_ngay3 = new javax.swing.JLabel();
        text_lop = new javax.swing.JTextField();
        tieude_khoa = new javax.swing.JLabel();
        text_ngaykt = new javax.swing.JTextField();
        tieude = new javax.swing.JLabel();
        tieude_ngay4 = new javax.swing.JLabel();
        text_tensv = new javax.swing.JTextField();
        cb_lydo = new javax.swing.JComboBox<>();
        tieude_ngay = new javax.swing.JLabel();
        tieude_ngay5 = new javax.swing.JLabel();
        text_msv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_chitiet = new javax.swing.JTextArea();
        text_khoa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rb_co = new javax.swing.JRadioButton();
        rb_khong = new javax.swing.JRadioButton();
        bt_gui1 = new javax.swing.JButton();
        menu_gv = new javax.swing.JMenuBar();
        m_gvTrangChu = new javax.swing.JMenu();
        m_gvTroGiup = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text_ngay.setEditable(false);
        text_ngay.setText(d.getNgayGui());
        text_ngay.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_ngay.setFocusable(false);
        text_ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ngayActionPerformed(evt);
            }
        });

        tieude_ngay6.setText("Các tài liệu/hình ảnh liên quan:");

        bt_xem.setText("Mở file");
        bt_xem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_xemMouseClicked(evt);
            }
        });

        tieude_ngaybd.setText("Ngày bắt đầu");

        file_name.setText(d.getTaiLieuLienQuan());
        file_name.setFocusable(false);

        tieude_masv.setText("Mã sinh viên");

        text_ngaybd.setText(d.getNgayBatDau());
        text_ngaybd.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_ngaybd.setFocusable(false);
        text_ngaybd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ngaybdActionPerformed(evt);
            }
        });

        tieude_khoa1.setText("Lớp");

        tieude_tensv.setText("Tên sinh viên");

        tieude_ngay3.setText("Ngày kết thúc");

        text_lop.setEditable(false);
        text_lop.setText(d.getLop());
        text_lop.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_lop.setFocusable(false);
        text_lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_lopActionPerformed(evt);
            }
        });

        tieude_khoa.setText("Khoa");

        text_ngaykt.setText(d.getNgayKetThuc());
        text_ngaykt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_ngaykt.setFocusable(false);
        text_ngaykt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ngayktActionPerformed(evt);
            }
        });

        tieude.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tieude.setText("Đơn Xin Nghỉ Phép");

        tieude_ngay4.setText("Lý do xin nghỉ");

        text_tensv.setEditable(false);
        text_tensv.setText(d.getTenSV());
        text_tensv.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_tensv.setFocusable(false);
        text_tensv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tensvActionPerformed(evt);
            }
        });

        cb_lydo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ốm nhập viện", "Việc cá nhân", "Mắc Covid-19", "Khác" }));
        cb_lydo.setSelectedIndex(getIndex());
        cb_lydo.setFocusable(false);
        cb_lydo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_lydoActionPerformed(evt);
            }
        });

        tieude_ngay.setText("Ngày gửi");

        tieude_ngay5.setText("Mô tả chi tiết:");

        text_msv.setEditable(false);
        text_msv.setText(d.getMaSV());
        text_msv.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_msv.setFocusable(false);
        text_msv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_msvActionPerformed(evt);
            }
        });

        text_chitiet.setColumns(20);
        text_chitiet.setRows(5);
        text_chitiet.setText(d.getChiTiet());
        text_chitiet.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_chitiet.setFocusable(false);
        jScrollPane1.setViewportView(text_chitiet);

        text_khoa.setEditable(false);
        text_khoa.setText(d.getKhoa());
        text_khoa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_khoa.setFocusable(false);
        text_khoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_khoaActionPerformed(evt);
            }
        });

        jLabel5.setText("Bạn có muốn tham gia lớp học trực tuyến không?");

        rb_co.setSelected(d.isHocOnl());
        rb_co.setText("Có");
        rb_co.setFocusable(false);
        rb_co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_coActionPerformed(evt);
            }
        });

        rb_khong.setSelected(!d.isHocOnl());
        rb_khong.setText("Không");
        rb_khong.setFocusable(false);
        rb_khong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_khongActionPerformed(evt);
            }
        });

        bt_gui1.setText("Đóng");
        bt_gui1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_gui1MouseClicked(evt);
            }
        });

        m_gvTrangChu.setText("Trang Chủ");
        m_gvTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_gvTrangChuMouseClicked(evt);
            }
        });
        menu_gv.add(m_gvTrangChu);

        m_gvTroGiup.setText("Trợ Giúp");
        menu_gv.add(m_gvTroGiup);

        setJMenuBar(menu_gv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(rb_co, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rb_khong, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tieude_ngay5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(tieude_ngay6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_gui1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_xem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(file_name, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tieude_ngay4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tieude_tensv)
                            .addComponent(tieude_masv))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text_msv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(text_tensv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_lydo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tieude_khoa1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tieude_khoa, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tieude_ngay, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tieude_ngay3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tieude_ngaybd, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(text_ngaykt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(text_ngaybd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(text_lop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(text_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tieude, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tieude, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tieude_ngay)
                        .addGap(27, 27, 27)
                        .addComponent(tieude_khoa)
                        .addGap(29, 29, 29)
                        .addComponent(tieude_khoa1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cb_lydo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tieude_ngay4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_msv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tieude_masv))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_tensv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tieude_tensv)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(text_lop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(tieude_ngaybd)
                                        .addGap(27, 27, 27)
                                        .addComponent(tieude_ngay3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(text_ngaybd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(text_ngaykt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_co)
                    .addComponent(rb_khong)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tieude_ngay5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(tieude_ngay6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(file_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_xem)))
                .addGap(27, 27, 27)
                .addComponent(bt_gui1)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_tensvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tensvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tensvActionPerformed

    private void cb_lydoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_lydoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_lydoActionPerformed

    private void text_msvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_msvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_msvActionPerformed

    private void m_gvTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_gvTrangChuMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_m_gvTrangChuMouseClicked

    private void bt_xemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_xemMouseClicked
        // TODO add your handling code here:
        
    if (Desktop.isDesktopSupported()) {
        
            // TODO add your handling code here:
            File file = new File("./src/images/"+d.getTaiLieuLienQuan());//đường dẫn file
            Desktop dt = Desktop.getDesktop();
        try {
            dt.open(file);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(SVXinNghiChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }
    else {
      throw new UnsupportedOperationException("Browser not supported.");
    
    }

    }//GEN-LAST:event_bt_xemMouseClicked

    private void rb_coActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_coActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_coActionPerformed

    private void rb_khongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_khongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_khongActionPerformed

    private void text_ngayktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ngayktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ngayktActionPerformed

    private void text_ngaybdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ngaybdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ngaybdActionPerformed

    private void text_lopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_lopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_lopActionPerformed

    private void text_khoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_khoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_khoaActionPerformed

    private void text_ngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ngayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ngayActionPerformed

    private void bt_gui1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_gui1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_gui1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SVXinNghiChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SVXinNghiChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SVXinNghiChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SVXinNghiChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SVXinNghiChiTiet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_gui1;
    private javax.swing.JButton bt_xem;
    private javax.swing.JComboBox<String> cb_lydo;
    private javax.swing.JLabel file_name;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu m_gvTrangChu;
    private javax.swing.JMenu m_gvTroGiup;
    private javax.swing.JMenuBar menu_gv;
    private javax.swing.JRadioButton rb_co;
    private javax.swing.JRadioButton rb_khong;
    private javax.swing.JTextArea text_chitiet;
    private javax.swing.JTextField text_khoa;
    private javax.swing.JTextField text_lop;
    private javax.swing.JTextField text_msv;
    private javax.swing.JTextField text_ngay;
    private javax.swing.JTextField text_ngaybd;
    private javax.swing.JTextField text_ngaykt;
    private javax.swing.JTextField text_tensv;
    private javax.swing.JLabel tieude;
    private javax.swing.JLabel tieude_khoa;
    private javax.swing.JLabel tieude_khoa1;
    private javax.swing.JLabel tieude_masv;
    private javax.swing.JLabel tieude_ngay;
    private javax.swing.JLabel tieude_ngay3;
    private javax.swing.JLabel tieude_ngay4;
    private javax.swing.JLabel tieude_ngay5;
    private javax.swing.JLabel tieude_ngay6;
    private javax.swing.JLabel tieude_ngaybd;
    private javax.swing.JLabel tieude_tensv;
    // End of variables declaration//GEN-END:variables
}
